import os


def env_bool(name: str, default: str = "0") -> bool:
    return os.getenv(name, default).lower() in ("1", "true", "yes", "y", "on")


DRY_RUN = env_bool("DRY_RUN", "1")

ENABLE_WS = env_bool("ENABLE_WS", "1")
ENABLE_DEX = env_bool("ENABLE_DEX", "1")
ENABLE_DISCORD = env_bool("ENABLE_DISCORD", "0")
ENABLE_WALLET = env_bool("ENABLE_WALLET", "0")

ENABLE_LOGS_SUB = env_bool("ENABLE_LOGS_SUB", "1")
ENABLE_WS_EARLY = env_bool("ENABLE_WS_EARLY", "1")
ENABLE_LOGS_TX_LOOKUP = env_bool("ENABLE_LOGS_TX_LOOKUP", "1")

ENABLE_FORENSICS = env_bool("ENABLE_FORENSICS", "1")
ENABLE_ATTENTION = env_bool("ENABLE_ATTENTION", "1")
ENABLE_EXECUTION = env_bool("ENABLE_EXECUTION", "0")
ENABLE_RISK_VETO = env_bool("ENABLE_RISK_VETO", "0")
ENABLE_ATTENTION_BONUS = env_bool("ENABLE_ATTENTION_BONUS", "0")
ENABLE_PUMPORTAL = env_bool("ENABLE_PUMPORTAL", "0")
ENABLE_BIRDEYE = env_bool("ENABLE_BIRDEYE", "0")
ENABLE_ATTENTION_CANDIDATE = env_bool("ENABLE_ATTENTION_CANDIDATE", "1")

DISCORD_WEBHOOK_URL = os.getenv("DISCORD_WEBHOOK_URL", "").strip()
DISCORD_CANDIDATE_WEBHOOK = os.getenv("DISCORD_CANDIDATE_WEBHOOK", "").strip()

HELIUS_WS_URL = os.getenv("HELIUS_WS_URL", "").strip()
HELIUS_API_KEY = os.getenv("HELIUS_API_KEY", "").strip()
HELIUS_RPC_URL = os.getenv("HELIUS_RPC_URL", "").strip()
BIRDEYE_API_KEY = os.getenv("BIRDEYE_API_KEY", "").strip()

PUMPFUN_PROGRAM_ID = "6EF8rrecthR5Dkzon8NFybJ9eQk6UkDBeo3xjT2f1gk"
RAYDIUM_AMM_PROGRAM_ID = "RVKd61ztZW9nhE7ztUj8iDSHPkS7cBvCqYJbF5v7Cwo"

DEX_REFRESH_SECONDS = int(os.getenv("DEX_REFRESH_SECONDS", "10"))
PROMOTE_MIN_CONFIDENCE = float(os.getenv("PROMOTE_MIN_CONFIDENCE", "0.65"))

RISK_VETO_THRESHOLD = float(os.getenv("RISK_VETO_THRESHOLD", "0.80"))
ATTENTION_BONUS_CAP = float(os.getenv("ATTENTION_BONUS_CAP", "0.15"))
ATTENTION_MIN_FOR_WINDOW = float(os.getenv("ATTENTION_MIN_FOR_WINDOW", "0.75"))
ATTENTION_WINDOW_MINUTES = int(os.getenv("ATTENTION_WINDOW_MINUTES", "60"))
ATTENTION_CANDIDATE_THRESHOLD = float(os.getenv("ATTENTION_CANDIDATE_THRESHOLD", "0.70"))
CAND_MIN_TOKEN_AGE_SEC = int(os.getenv("CAND_MIN_TOKEN_AGE_SEC", "30"))
EARLY_ATTENTION_MIN = float(os.getenv("EARLY_ATTENTION_MIN", "0.20"))
EARLY_CREATOR_MIN = float(os.getenv("EARLY_CREATOR_MIN", "0.30"))
EARLY_WATCH_RATE_LIMIT_PER_HOUR = int(os.getenv("EARLY_WATCH_RATE_LIMIT_PER_HOUR", "5"))
PROGRESSION_ATTENTION_DELTA = float(os.getenv("PROGRESSION_ATTENTION_DELTA", "0.10"))
PROGRESSION_BUYER_DELTA = float(os.getenv("PROGRESSION_BUYER_DELTA", "5"))
PROGRESSION_LIQ_DELTA = float(os.getenv("PROGRESSION_LIQ_DELTA", "0.20"))
PROGRESSION_SCORE_DELTA = float(os.getenv("PROGRESSION_SCORE_DELTA", "0.05"))
CAND_MIN_CURVE_LIQ_USD = float(os.getenv("CAND_MIN_CURVE_LIQ_USD", "500"))
PROM_MIN_LIQ_USD = float(os.getenv("PROM_MIN_LIQ_USD", "15000"))
PROMOTION_MIN_ATTENTION = float(os.getenv("PROMOTION_MIN_ATTENTION", "0.50"))
PROMOTION_MAX_RISK = float(os.getenv("PROMOTION_MAX_RISK", "0.60"))
CREATOR_RISK_WEIGHT = float(os.getenv("CREATOR_RISK_WEIGHT", "0.20"))
EXECUTION_BONUS_CAP = float(os.getenv("EXECUTION_BONUS_CAP", "0.05"))
MIN_EDGE_BPS = float(os.getenv("MIN_EDGE_BPS", "80"))

ENGINE_MODE = os.getenv("ENGINE_MODE", "balanced")  # balanced | sniper | long_term

# ignore dust buys for attention (still can log if you want)
MIN_BUY_SOL_FOR_ATTENTION_SNIPER = float(os.getenv("MIN_BUY_SOL_FOR_ATTENTION_SNIPER", "0.01"))
MIN_BUY_SOL_FOR_ATTENTION_LONG = float(os.getenv("MIN_BUY_SOL_FOR_ATTENTION_LONG", "0.10"))

# long-term stricter requirements
LONG_MIN_UNIQUE_BUYERS_5M = int(os.getenv("LONG_MIN_UNIQUE_BUYERS_5M", "4"))
LONG_MIN_ELITE_SCORE = int(os.getenv("LONG_MIN_ELITE_SCORE", "10"))

# sniper bypass parameters
SNIPER_MIN_UNIQUE_10S = int(os.getenv("SNIPER_MIN_UNIQUE_10S", "2"))
SNIPER_MIN_BURST10S = int(os.getenv("SNIPER_MIN_BURST10S", "6"))
SNIPER_MIN_ELITE_SCORE = int(os.getenv("SNIPER_MIN_ELITE_SCORE", "8"))
AGE_BYPASS_TTL_SECONDS = int(os.getenv("AGE_BYPASS_TTL_SECONDS", "20"))

# momentum decay blacklist
DECAY_WINDOW_SECONDS = int(os.getenv("DECAY_WINDOW_SECONDS", "20"))
BLACKLIST_SECONDS = int(os.getenv("BLACKLIST_SECONDS", "600"))

# Discord embed regime thresholds
RADAR_QUIET_RISK_MAX = float(os.getenv("RADAR_QUIET_RISK_MAX", "0.25"))

# Dedupe / cooldown
EARLY_DEDUPE_TTL_SEC = int(os.getenv("EARLY_DEDUPE_TTL_SEC", "600"))
ALERT_COOLDOWN_SEC = int(os.getenv("ALERT_COOLDOWN_SEC", "120"))

# Alert admission gate (layered quality filters)
ENABLE_ALERT_GATE = env_bool("ENABLE_ALERT_GATE", "1")
GATE_REQUIRE_DEX = env_bool("GATE_REQUIRE_DEX", "1")

# Deprecated: legacy static alert gates (kept for rollback testing)
GATE_HEATING_MIN_LIQ = float(os.getenv("GATE_HEATING_MIN_LIQ", "3000"))
GATE_HEATING_MIN_VOL5M = float(os.getenv("GATE_HEATING_MIN_VOL5M", "800"))
GATE_HEATING_MIN_BUYS5M = int(os.getenv("GATE_HEATING_MIN_BUYS5M", "5"))
GATE_HEATING_MAX_SELL_RATIO5M = float(os.getenv("GATE_HEATING_MAX_SELL_RATIO5M", "2.5"))
GATE_HEATING_MAX_VOL_LIQ_RATIO5M = float(os.getenv("GATE_HEATING_MAX_VOL_LIQ_RATIO5M", "10"))
GATE_HEATING_MIN_AGE_MIN = float(os.getenv("GATE_HEATING_MIN_AGE_MIN", "1.0"))
GATE_HEATING_MAX_PRICE_DROP5M = float(os.getenv("GATE_HEATING_MAX_PRICE_DROP5M", "-20"))

GATE_PROMOTE_MIN_LIQ = float(os.getenv("GATE_PROMOTE_MIN_LIQ", "15000"))
GATE_PROMOTE_MIN_VOL5M = float(os.getenv("GATE_PROMOTE_MIN_VOL5M", "8000"))
GATE_PROMOTE_MIN_BUYS5M = int(os.getenv("GATE_PROMOTE_MIN_BUYS5M", "15"))
GATE_PROMOTE_MAX_SELL_RATIO5M = float(os.getenv("GATE_PROMOTE_MAX_SELL_RATIO5M", "1.5"))
GATE_PROMOTE_MAX_VOL_LIQ_RATIO5M = float(os.getenv("GATE_PROMOTE_MAX_VOL_LIQ_RATIO5M", "6"))
GATE_PROMOTE_MIN_AGE_MIN = float(os.getenv("GATE_PROMOTE_MIN_AGE_MIN", "2.0"))
GATE_PROMOTE_MAX_PRICE_DROP5M = float(os.getenv("GATE_PROMOTE_MAX_PRICE_DROP5M", "-10"))
